databases:
      - name: paw_finder_production
        databaseName: paw_finder_production
        user: paw_finder

  services:
      - type: web
        name: paw_finder
        env: ruby
        buildCommand: "./bin/render-build.sh"
        startCommand: "bundle exec puma -C config/puma.rb"
        envVars:
          - key: DATABASE_URL
            fromDatabase:
              name: paw_finder_production
              property: connectionString
          - key: RAILS_MASTER_KEY
            sync: false